### ISSUE TITLE
Homework #2

### ISSUE THREAD

**Issue by kamontat** [kamontat/Portfolio-old#47]
Designing your website. Using latest version of development branch.

## Task

- [ ] Copy content from one of topic in medium that you wrote
- [ ] Paste in the `/topic` path
- [ ] Design your content to show to client

## Main responsibility of your design

- [ ] Easy to read
- [ ] Work on both `Mobile` and `Website`

## Learn lesson

- [ ] REACT - Able to create new react component and know how to use it
- [ ] CSS - design website using `class`, `id`
- [ ] SCSS Variable - Able to create scss variable and use it
- [ ] Readable - can read any of `javascript`, `css` or `scss` code
